### ISSUE TITLE
Container fails to start: `unable to open database file: out of memory (14)`

### ISSUE THREAD

**Issue by epk** [tailscale/golink#6]
Running a minimal container with no volume mounts results in
```bash
docker run --rm ghcr.io/tailscale/golink:main
2022/11/14 14:34:02 NewSQLiteDB("/root/golink.db"): unable to open database file: out of memory (14)
```
or 
```yaml
version: "3"
services:
  golink:
    image: ghcr.io/tailscale/golink:main
    container_name: golink
    restart: unless-stopped
    command: "-verbose -sqlitedb /root/golink.db"
```

```
2022/11/14 14:30:55 NewSQLiteDB("/root/golink.db"): unable to open database file: out of memory (14)
```

---

However, running and building the binary directly works without an issue:
```
go run github.com/tailscale/golink/cmd/golink@latest -verbose -sqlitedb /persist/golink/golink.db
```

**Comment by parkr** [comment]
Hey, this happened for me too. It's due to the `static` / `scratch` image not playing nice with the Go bindings for sqlite.

To fix, I created a new Dockerfile which used a basic image:

```dockerfile
FROM ghcr.io/tailscale/golink:main as golink

FROM debian:stable-slim

COPY --from=golink /golink /golink
```

I ran `docker build -t golink .` and `docker run -it -e "TS_AUTHKEY=tskey-auth-...." --rm --name golink -v /opt/golink/data:/root/.config/tsnet-golink golink /golink -sqlitedb golink.db -verbose` and it worked for me. 

I did have an issue where my authkey was invalidated accidentally, but that's not relevant to this issue.

**Comment by willnorris** [comment]
@parkr is that really the cause?  Interesting.  I think I recall seeing that also if I didn't map a volume for /root.  If that's the case, I can update the docs to make it clear that the volume mounting is required.

**Comment by kurtraschke** [comment]
I can't claim that this is the _only_ cause of this failure, but in my experience this stemmed from the fact that `golink` runs in `cgr.dev/chainguard/static` as uid:gid 65532:65532 ([as documented](https://github.com/chainguard-images/static#users)), but a Docker named volume mount is, by default, owned by `root` inside the container.  Creating a local directory owned by 65532:65532 and mounting that as a volume at `/root` inside the container worked for me, as well as using a one-off utility container to change the permissions of a named volume.

**Comment by willnorris** [comment]
hmm... @dlorenc @imjasonh what's the recommended way to handle this? I'd very much like to continue using wolfi images.

**Comment by willnorris** [comment]
okay... I finally have a reproduction case.  I think it was because (as @parkr noted above) this is an amd64 issue, and I was testing on arm64.  Now that I can reproduce, I'll experiment more in the morning.

**Comment by amouat** [comment]
I just had a quick look at this. @epk if you add `user: root` to your compose file, it should work:

```
version: "3"
services:
  golink:
    image: ghcr.io/tailscale/golink:main
    container_name: golink
    restart: unless-stopped
    user: root
    command: "-verbose -sqlitedb /root/golink.db"
```
